### ISSUE TITLE
"Resource not accessible by integration" error

### ISSUE THREAD

**Issue by nikp123** [jayqi/failed-build-issue-action#117]
I had a very funny failure, so lets not repeat mistakes if possible.
![image](https://github.com/jayqi/failed-build-issue-action/assets/4696350/9e9a06f5-2347-40de-b983-6cbb2ab65423)

**Comment by nikp123** [comment]
![image](https://github.com/jayqi/failed-build-issue-action/assets/4696350/fe71c7cc-21ce-4ee6-ab5c-676422a91fa8)
ok it seems it might be something else even

**Comment by jayqi** [comment]
Are you running this on a public repository you're able to link for me to help you debug?

As you mentioned in your follow up, this Action is supposed by default create the issue label for you if it doesn't already exist. This is controlled by the [`create-label` parameter](https://github.com/jayqi/failed-build-issue-action/blob/f036362925e23e853c68f07ae7f4090b5b5c2786/action.yml#L26C3-L29).

**Comment by nikp123** [comment]
> Are you running this on a public repository you're able to link for me to help you debug?

Yes, actually.
https://github.com/nikp123/nur-packages/actions

Here's one of the actions that failed:
https://github.com/nikp123/nur-packages/actions/runs/9867435838/job/27247900607

Please tell me what I need to do to help you debug this.

PS: Sorry in advance but I may be slow to respond due to other tasks

**Comment by jayqi** [comment]
Hi @nikp123,

One thing I would check is whether you have given GitHub Actions workflows the necessary permissions in this repository. I believe that "Read and write permissions" are necessary. You can find this setting in `Settings` > `Actions` > `General` for your repository.

![Screenshot 2024-07-11 at 5 17 52 PM](https://github.com/user-attachments/assets/96776681-3e36-48f5-80a8-6b02d9130b92)

Otherwise, take a look at a look at the suggested steps in [this response](https://github.com/orgs/community/discussions/60820#discussioncomment-6445767). In general, this error message seems to be related to GitHub Actions having necessary permissions to perform some task.

**Comment by nikp123** [comment]
@jayqi That was it, thank you.

EDIT: Please add this to the README as it won't be completely obvious to people who aren't familiar with GitHub Actions
